require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SubmittedLinksController do

  def mock_submitted_link(stubs={})
    @mock_submitted_link ||= mock_model(SubmittedLink, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all submitted_links as @submitted_links" do
      SubmittedLink.stub(:all) { [mock_submitted_link] }
      get :index
      assigns(:submitted_links).should eq([mock_submitted_link])
    end
  end

  describe "GET show" do
    it "assigns the requested submitted_link as @submitted_link" do
      SubmittedLink.stub(:find).with("37") { mock_submitted_link }
      get :show, :id => "37"
      assigns(:submitted_link).should be(mock_submitted_link)
    end
  end

  describe "GET new" do
    it "assigns a new submitted_link as @submitted_link" do
      SubmittedLink.stub(:new) { mock_submitted_link }
      get :new
      assigns(:submitted_link).should be(mock_submitted_link)
    end
  end

  describe "GET edit" do
    it "assigns the requested submitted_link as @submitted_link" do
      SubmittedLink.stub(:find).with("37") { mock_submitted_link }
      get :edit, :id => "37"
      assigns(:submitted_link).should be(mock_submitted_link)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created submitted_link as @submitted_link" do
        SubmittedLink.stub(:new).with({'these' => 'params'}) { mock_submitted_link(:save => true) }
        post :create, :submitted_link => {'these' => 'params'}
        assigns(:submitted_link).should be(mock_submitted_link)
      end

      it "redirects to the created submitted_link" do
        SubmittedLink.stub(:new) { mock_submitted_link(:save => true) }
        post :create, :submitted_link => {}
        response.should redirect_to(submitted_link_url(mock_submitted_link))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved submitted_link as @submitted_link" do
        SubmittedLink.stub(:new).with({'these' => 'params'}) { mock_submitted_link(:save => false) }
        post :create, :submitted_link => {'these' => 'params'}
        assigns(:submitted_link).should be(mock_submitted_link)
      end

      it "re-renders the 'new' template" do
        SubmittedLink.stub(:new) { mock_submitted_link(:save => false) }
        post :create, :submitted_link => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested submitted_link" do
        SubmittedLink.stub(:find).with("37") { mock_submitted_link }
        mock_submitted_link.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :submitted_link => {'these' => 'params'}
      end

      it "assigns the requested submitted_link as @submitted_link" do
        SubmittedLink.stub(:find) { mock_submitted_link(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:submitted_link).should be(mock_submitted_link)
      end

      it "redirects to the submitted_link" do
        SubmittedLink.stub(:find) { mock_submitted_link(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(submitted_link_url(mock_submitted_link))
      end
    end

    describe "with invalid params" do
      it "assigns the submitted_link as @submitted_link" do
        SubmittedLink.stub(:find) { mock_submitted_link(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:submitted_link).should be(mock_submitted_link)
      end

      it "re-renders the 'edit' template" do
        SubmittedLink.stub(:find) { mock_submitted_link(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested submitted_link" do
      SubmittedLink.stub(:find).with("37") { mock_submitted_link }
      mock_submitted_link.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the submitted_links list" do
      SubmittedLink.stub(:find) { mock_submitted_link }
      delete :destroy, :id => "1"
      response.should redirect_to(submitted_links_url)
    end
  end

end
